Update docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -19,6 +19,16 @@ jobs:
           ls
           cp webapp/target/webapp.war webapp.war
           ls -l -a
+      - name: Verify WebApp WAR File
+        run: |
+          ls -l webapp/target/
+          if [ -f "webapp/target/webapp.war" ]; then
+            echo "webapp.war exists!"
+            cp webapp/target/webapp.war webapp.war
+          else
+            echo "webapp.war not found!"
+            exit 1
+          fi
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
